In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [3]:
df_energy = pd.read_csv("../data/raw/global-data-on-sustainable-energy.csv")
print(df_energy.info())

<class 'pandas.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 18 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   str
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density(P/Km2)                                                    3648 non-null   str
dtypes: float64(15), int64(1), str(2)
memory usage: 513.3 KB
None

In [4]:
df_energy["Density(P/Km2)"] = (
    df_energy["Density(P/Km2)"].str.replace(",", "").astype(float)
)
df_energy['Density(P/Km2)'].dtype

dtype('float64')

In [5]:
df_info = df_energy.describe().transpose()
missing_values = df_energy.isna().sum()
print(missing_values)

Entity                                                                 0
Year                                                                   0
Access to electricity (% of population)                               10
Access to clean fuels for cooking                                    169
Renewable-electricity-generating-capacity-per-capita                 931
Financial flows to developing countries (US $)                      2089
Renewable energy share in the total final energy consumption (%)     194
Electricity from fossil fuels (TWh)                                   21
Electricity from nuclear (TWh)                                       126
Electricity from renewables (TWh)                                     21
Low-carbon electricity (% electricity)                                42
Primary energy consumption per capita (kWh/person)                     0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          207
Value_co2_emissions_kt_by_country                                    428
Renewables (% equivalent primary energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
Density(P/Km2)                                                         1
dtype: int64

In [6]:
# Drop columns with a high number of missing values
df_energy.drop(
    columns=[
        "Financial flows to developing countries (US $)",
        "Renewables (% equivalent primary energy)",
        "Renewable-electricity-generating-capacity-per-capita",
    ],
    inplace=True,
)

In [7]:
# Fill missing values with mean
columns_to_fill_mean = [
    "Access to clean fuels for cooking",
    "Renewable energy share in the total final energy consumption (%)",
    "Electricity from nuclear (TWh)",
    "Energy intensity level of primary energy (MJ/$2017 PPP GDP)",
    "Value_co2_emissions_kt_by_country",
    "gdp_growth",
    "gdp_per_capita",
]
df_energy[columns_to_fill_mean] = df_energy[columns_to_fill_mean].apply(
    lambda x: x.fillna(x.mean())
)

In [8]:
df_energy = df_energy.dropna()

In [9]:
print(df_energy.isna().sum())

Entity                                                              0
Year                                                                0
Access to electricity (% of population)                             0
Access to clean fuels for cooking                                   0
Renewable energy share in the total final energy consumption (%)    0
Electricity from fossil fuels (TWh)                                 0
Electricity from nuclear (TWh)                                      0
Electricity from renewables (TWh)                                   0
Low-carbon electricity (% electricity)                              0
Primary energy consumption per capita (kWh/person)                  0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         0
Value_co2_emissions_kt_by_country                                   0
gdp_growth                                                          0
gdp_per_capita                                                      0
Density(P/Km2)                                                      0
dtype: int64

In [10]:
df_energy.describe()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,Density(P/Km2)
count,3597.000000,3597.000000,3597.000000,3597.000000,3597.000000,3597.000000,3597.000000,3597.000000,3597.000000,3597.000000,3.597000e+03,3597.000000,3597.000000,3597.000000
mean,2010.060606,78.705977,63.511656,32.845165,70.970904,13.566108,24.174573,36.903493,25847.609790,5.319477,1.619071e+05,3.473389,12912.009365,216.827912
std,6.047476,30.377246,38.225137,28.967416,349.487391,72.240651,104.856438,34.307566,34910.663771,3.418059,7.318720e+05,5.417731,17981.153678,683.326061
min,2000.000000,1.252269,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,105.110120,0.110000,3.000000e+01,-62.075920,111.927225,2.000000
25%,2005.000000,58.595592,25.900000,7.290000,0.310000,0.000000,0.050000,2.970297,3183.104700,3.240000,2.658575e+03,1.677898,1464.554009,31.000000
50%,2010.000000,98.279810,80.300000,27.160000,3.010000,0.000000,1.500000,28.120895,13215.600000,4.500000,1.903000e+04,3.441610,5413.776021,87.000000
75%,2015.000000,100.000000,100.000000,52.770000,27.170000,0.000000,9.800000,64.502170,33738.633000,5.880000,1.454200e+05,5.557264,13822.741750,214.000000
max,2020.000000,100.000000,100.000000,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,123.139555,123514.196700,8358.000000

In [11]:
df_energy = df_energy[
    [
        "Entity",
        "Year",
        "Access to electricity (% of population)",
        "Access to clean fuels for cooking",
        "Renewable energy share in the total final energy consumption (%)",
        "Electricity from fossil fuels (TWh)",
        "Electricity from nuclear (TWh)",
        "Electricity from renewables (TWh)",
        "Low-carbon electricity (% electricity)",
        "Primary energy consumption per capita (kWh/person)",
        "Density(P/Km2)",
        "gdp_per_capita",
    ]
]

In [12]:
df_energy['Total_electricity'] = (
    df_energy['Electricity from fossil fuels (TWh)'] +
    df_energy['Electricity from nuclear (TWh)'] +
    df_energy['Electricity from renewables (TWh)']
)

df_energy['Fossil_ratio'] = df_energy['Electricity from fossil fuels (TWh)'] / df_energy['Total_electricity']
df_energy['Renewable_ratio'] = df_energy['Electricity from renewables (TWh)'] / df_energy['Total_electricity']
df_energy['Nuclear_ratio'] = df_energy['Electricity from nuclear (TWh)'] / df_energy['Total_electricity']

In [13]:
df_energy['Energy_access_score'] = (
    df_energy['Access to electricity (% of population)'] * 0.6 +
    df_energy['Access to clean fuels for cooking'] * 0.4
)

In [14]:
df_energy["Fossil_per_capita"] = (
    df_energy["Electricity from fossil fuels (TWh)"] / df_energy["Density(P/Km2)"]
)
df_energy["Renewable_per_capita"] = (
    df_energy["Electricity from renewables (TWh)"] / df_energy["Density(P/Km2)"]
)

In [15]:
# Ensure data is sorted by country and year
df_energy.sort_values(['Entity', 'Year'], inplace=True)

# Calculate year-on-year percentage change for electricity sources
df_energy['Fossil_growth'] = df_energy.groupby('Entity')['Electricity from fossil fuels (TWh)'].pct_change() * 100
df_energy['Renewable_growth'] = df_energy.groupby('Entity')['Electricity from renewables (TWh)'].pct_change() * 100
df_energy['Total_energy_growth'] = df_energy.groupby('Entity')['Total_electricity'].pct_change() * 100

# Fill NaN values for the first year of each country with 0
df_energy['Fossil_growth'] = df_energy['Fossil_growth'].fillna(0)
df_energy['Renewable_growth'] = df_energy['Renewable_growth'].fillna(0)
df_energy['Total_energy_growth'] = df_energy['Total_energy_growth'].fillna(0)

# Optional: view first few rows to verify
df_energy[['Entity', 'Year', 'Fossil_growth', 'Renewable_growth', 'Total_energy_growth']].head(10)

        Entity  Year  Fossil_growth  Renewable_growth  Total_energy_growth
0  Afghanistan  2000       0.000000          0.000000             0.000000
1  Afghanistan  2001     -43.750000         61.290323            25.531915
2  Afghanistan  2002      44.444444         12.000000            16.949153
3  Afghanistan  2003     138.461538         12.500000            36.231884
4  Afghanistan  2004       6.451613        -11.111111            -5.319149
5  Afghanistan  2005       3.030303          5.357143             4.494382
6  Afghanistan  2006     -41.176471          8.474576            -9.677419
7  Afghanistan  2007       0.000000         17.187500            13.095238
8  Afghanistan  2008      -5.000000        -28.000000           -23.157895
9  Afghanistan  2009     -15.789474         44.444444            28.767123

In [16]:
df_energy.info()

<class 'pandas.DataFrame'>
Index: 3597 entries, 0 to 3648
Data columns (total 22 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3597 non-null   str
 1   Year                                                              3597 non-null   int64
 2   Access to electricity (% of population)                           3597 non-null   float64
 3   Access to clean fuels for cooking                                 3597 non-null   float64
 4   Renewable energy share in the total final energy consumption (%)  3597 non-null   float64
 5   Electricity from fossil fuels (TWh)                               3597 non-null   float64
 6   Electricity from nuclear (TWh)                                    3597 non-null   float64
 7   Electricity from renewables (TWh)                                 3597 non-null   float64
 8   Low-carbon electricity (% electricity)                            3597 non-null   float64
 9   Primary energy consumption per capita (kWh/person)                3597 non-null   float64
 10  Density(P/Km2)                                                    3597 non-null   float64
 11  gdp_per_capita                                                    3597 non-null   float64
 12  Total_electricity                                                 3597 non-null   float64
 13  Fossil_ratio                                                      3597 non-null   float64
 14  Renewable_ratio                                                   3597 non-null   float64
 15  Nuclear_ratio                                                     3597 non-null   float64
 16  Energy_access_score                                               3597 non-null   float64
 17  Fossil_per_capita                                                 3597 non-null   float64
 18  Renewable_per_capita                                              3597 non-null   float64
 19  Fossil_growth                                                     3597 non-null   float64
 20  Renewable_growth                                                  3597 non-null   float64
 21  Total_energy_growth                                               3597 non-null   float64
dtypes: float64(20), int64(1), str(1)
memory usage: 646.3 KB

In [17]:
scaler = MinMaxScaler()
df_energy[
    ["Fossil_ratio", "Renewable_ratio", "Nuclear_ratio", "Energy_access_score"]
] = scaler.fit_transform(
    df_energy[
        ["Fossil_ratio", "Renewable_ratio", "Nuclear_ratio", "Energy_access_score"]
    ]
)

In [18]:
print(df_energy.info())

<class 'pandas.DataFrame'>
Index: 3597 entries, 0 to 3648
Data columns (total 22 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3597 non-null   str
 1   Year                                                              3597 non-null   int64
 2   Access to electricity (% of population)                           3597 non-null   float64
 3   Access to clean fuels for cooking                                 3597 non-null   float64
 4   Renewable energy share in the total final energy consumption (%)  3597 non-null   float64
 5   Electricity from fossil fuels (TWh)                               3597 non-null   float64
 6   Electricity from nuclear (TWh)                                    3597 non-null   float64
 7   Electricity from renewables (TWh)                                 3597 non-null   float64
 8   Low-carbon electricity (% electricity)                            3597 non-null   float64
 9   Primary energy consumption per capita (kWh/person)                3597 non-null   float64
 10  Density(P/Km2)                                                    3597 non-null   float64
 11  gdp_per_capita                                                    3597 non-null   float64
 12  Total_electricity                                                 3597 non-null   float64
 13  Fossil_ratio                                                      3597 non-null   float64
 14  Renewable_ratio                                                   3597 non-null   float64
 15  Nuclear_ratio                                                     3597 non-null   float64
 16  Energy_access_score                                               3597 non-null   float64
 17  Fossil_per_capita                                                 3597 non-null   float64
 18  Renewable_per_capita                                              3597 non-null   float64
 19  Fossil_growth                                                     3597 non-null   float64
 20  Renewable_growth                                                  3597 non-null   float64
 21  Total_energy_growth                                               3597 non-null   float64
dtypes: float64(20), int64(1), str(1)
memory usage: 646.3 KB
None

In [ ]:
cols_to_keep = [
    'Entity', 'Year', 'Total_electricity', 'Fossil_ratio', 'Renewable_ratio',
    'Nuclear_ratio', 'Energy_access_score', 'Fossil_per_capita',
    'Renewable_per_capita', 'Fossil_growth', 'Renewable_growth', 'Total_energy_growth'
]

df_energy_plot = df_energy[cols_to_keep].copy()

print(df_energy_plot.describe())

              Year  Total_electricity  Fossil_ratio  Renewable_ratio  \
count  3597.000000        3597.000000   3597.000000      3597.000000
mean   2010.060606         108.711585      0.628348         0.326121
std       6.047476         490.250517      0.341979         0.333024
min    2000.000000           0.010000      0.000000         0.000000
25%    2005.000000           0.960000      0.354978         0.023810
50%    2010.000000           9.250000      0.718240         0.186036
75%    2015.000000          49.930000      0.965447         0.586667
max    2020.000000        7735.270000      1.000000         1.000000

       Nuclear_ratio  Energy_access_score  Fossil_per_capita  \
count    3597.000000          3597.000000        3597.000000
mean        0.054884             0.723720           1.665746
std         0.154266             0.326520           8.399551
min         0.000000             0.000000           0.000000
25%         0.000000             0.441802           0.003200
50%         0.000000             0.884785           0.049643
75%         0.000000             1.000000           0.308594
max         1.000000             1.000000          83.006667

       Renewable_per_capita  Fossil_growth  Renewable_growth  \
count           3597.000000    3597.000000       3597.000000
mean               1.079668            inf               inf
std                7.677636            NaN               NaN
min                0.000000    -100.000000       -100.000000
25%                0.000454      -1.346801          0.000000
50%                0.021573       1.091703          0.000000
75%                0.139320       7.692308         11.174785
max              108.857500            inf               inf

       Total_energy_growth
count          3597.000000
mean              4.010847
std              13.655464
min             -78.048780
25%               0.000000
50%               2.366864
75%               6.760563
max             221.839080

/home/abhi/Code/python_projects/data-viz-group/venv/lib64/python3.14/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/home/abhi/Code/python_projects/data-viz-group/venv/lib64/python3.14/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

In [21]:
df_energy.to_csv("../data/processed/energy_cleaned.csv", index=False)